name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.51.0
          override: true
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: pr-build-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check against lib
        working-directory: .
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test against lib
        working-directory: .
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo fmt against lib
        working-directory: .
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy against lib
        working-directory: .
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo check against examples
        working-directory: examples
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test against examples
        working-directory: examples
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo fmt against examples
        working-directory: examples
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy against examples
        working-directory: examples
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
